pr:
  branches:
    include:
      - main
      
trigger: none

pool:
  vmImage: ubuntu-latest

stages:
# Stage 1
- stage: Build
  displayName: 'Dummy Build Stage'
  jobs:
  - job: BuildJob
    displayName: 'Build Job'
    steps:
    - script: echo "This is the Build stage"
      displayName: 'Print Build Message'

# Stage 2
- stage: Test
  displayName: 'Dummy Test Stage'
  dependsOn: Build   # Ensures this runs after Build stage
  jobs:
  - job: TestJob
    displayName: 'Test Job'
    steps:
    - script: echo "This is the Test stage"
      displayName: 'Print Test Message'
