pr:
  branches:
    include:
      - main
      
trigger: none

pool:
  vmImage: ubuntu-latest

stages:
# Stage 1
- stage: Build
  displayName: 'Dummy Build Stage'
  jobs:
  - job: BuildJob
    displayName: 'Build Job'
    steps:
    - script: echo "This is the Build stage"
      displayName: 'Print Build Message'

# Stage 2
- stage: Test
  displayName: 'Dummy Test Stage'
  dependsOn: Build   # Ensures this runs after Build stage
  jobs:
  - job: TestJob
    displayName: 'Test Job'
    steps:
    - script: echo "This is the Test stage"
      displayName: 'Print Test Message'
  - job: changelog
    displayName: 'log check'
    steps:
    - script: |
        git fetch origin +refs/heads/*:refs/remotes/origin/*
        TARGET_BRANCH=$(System.PullRequest.TargetBranch)
        TARGET_BRANCH=${TARGET_BRANCH#refs/heads/}
        echo "Comparing against: $TARGET_BRANCH"
        
        if git diff origin/$TARGET_BRANCH HEAD -- changelog.md \
          | grep '^+' | grep -v '^+++' > /dev/null; then
          echo "New lines were added to changelog.md. Pipeline will continue."
        else
          echo "No new lines added to changelog.md. Failing the pipeline."
          exit 1
        fi
      displayName: 'Check for Changelog Update'

